import { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, RotateCcw, CheckCircle2, Star } from 'lucide-react';
import Hero from '../components/Hero';
import Features from '../components/Features';
import UploadCard from '../components/UploadCard';
import ATSScore from '../components/ATSScore';
import SkillChart from '../components/SkillChart';
import Footer from '../components/Footer';

const testimonials = [
  { name:'Alex M.',  role:'Software Engineer',     text:'Went from 0 callbacks to 4 interviews in 2 weeks. The ATS score told me exactly what was wrong.',  rating:5, avatar:'AM' },
  { name:'Priya K.', role:'Product Manager',       text:'The skill gap analysis was eye-opening. Added the missing keywords and my match rate jumped to 91%.', rating:5, avatar:'PK' },
  { name:'James T.', role:'Data Scientist',        text:'Best free resume tool I\'ve used. Clean, fast, and the AI tips are actually specific and useful.',    rating:5, avatar:'JT' },
];

export default function Home() {
  const [result, setResult] = useState(null);
  const [fileName, setFileName] = useState('');
  const resultsRef = useRef(null);

  const handleResult = (data, name) => {
    setResult(data); setFileName(name);
    setTimeout(() => resultsRef.current?.scrollIntoView({behavior:'smooth', block:'start'}), 100);
  };

  return (
    <div className="min-h-screen">
      <Hero />
      <Features />

      {/* ── Analyzer section ── */}
      <section id="analyzer" className="bg-slate-50 py-24 px-6">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-12">
            <motion.p initial={{opacity:0}} whileInView={{opacity:1}} viewport={{once:true}}
              className="text-emerald-600 text-sm font-bold uppercase tracking-widest mb-3">
              Free Resume Checker
            </motion.p>
            <motion.h2 initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}
              className="text-4xl md:text-5xl font-extrabold text-slate-900 mb-4">
              Check your resume right now
            </motion.h2>
            <motion.p initial={{opacity:0}} whileInView={{opacity:1}} viewport={{once:true}} transition={{delay:0.1}}
              className="text-slate-500 text-lg max-w-xl mx-auto">
              No account needed. Upload your resume and get instant AI feedback in under 30 seconds.
            </motion.p>
          </div>

          <AnimatePresence mode="wait">
            {!result ? (
              <motion.div key="upload" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}}>
                <div className="bg-white rounded-2xl p-8 border border-slate-100" style={{boxShadow:'0 4px 24px rgba(0,0,0,0.06)'}}>
                  <UploadCard onResult={handleResult}/>
                </div>
              </motion.div>
            ) : (
              <motion.div key="results" ref={resultsRef}
                initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:0.6}}>
                {/* Result header */}
                <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-emerald-100 border border-emerald-200 flex items-center justify-center">
                      <FileText size={20} className="text-emerald-600"/>
                    </div>
                    <div>
                      <p className="text-slate-900 font-bold">{fileName}</p>
                      <p className="text-slate-400 text-xs flex items-center gap-1">
                        <CheckCircle2 size={11} className="text-emerald-500"/> Analysis complete
                      </p>
                    </div>
                  </div>
                  <button onClick={() => { setResult(null); setFileName(''); }}
                    className="flex items-center gap-1.5 px-4 py-2 rounded-xl text-sm font-medium text-slate-600 bg-white border border-slate-200 hover:border-slate-300 transition-all">
                    <RotateCcw size={14}/> Analyze another
                  </button>
                </div>

                {/* Results grid */}
                <div className="grid grid-cols-1 lg:grid-cols-5 gap-5">
                  <div className="lg:col-span-2">
                    <ATSScore atsScore={result.atsScore} jobMatchScore={result.jobMatchScore}/>
                  </div>
                  <div className="lg:col-span-3">
                    <SkillChart data={result}/>
                  </div>
                </div>

                <p className="text-center text-slate-400 text-xs mt-5">
                  Results generated by Gemini AI · Your resume was never stored · Refresh to start over
                </p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </section>

      {/* ── Testimonials ── */}
      <section className="bg-white py-24 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="text-center mb-14">
            <motion.h2 initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}
              className="text-4xl font-extrabold text-slate-900">
              Real results from real people
            </motion.h2>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {testimonials.map(({name,role,text,rating,avatar},i) => (
              <motion.div key={name}
                initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}}
                transition={{delay:i*0.1,duration:0.5}}
                className="bg-slate-50 rounded-2xl p-6 border border-slate-100 hover:border-indigo-200 transition-all hover:shadow-md">
                <div className="flex gap-0.5 mb-4">
                  {Array.from({length:rating}).map((_,j) => (
                    <Star key={j} size={15} className="text-amber-400 fill-amber-400"/>
                  ))}
                </div>
                <p className="text-slate-700 text-sm leading-relaxed mb-5">"{text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-full flex items-center justify-center text-white text-sm font-bold"
                    style={{background:'linear-gradient(135deg,#6366f1,#8b5cf6)'}}>
                    {avatar}
                  </div>
                  <div>
                    <p className="text-slate-900 font-semibold text-sm">{name}</p>
                    <p className="text-slate-400 text-xs">{role}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Final CTA ── */}
      <section className="dark-section py-24 px-6">
        <div className="max-w-3xl mx-auto text-center">
          <motion.h2 initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}
            className="text-4xl md:text-5xl font-extrabold text-white mb-6">
            Ready to land more interviews?
          </motion.h2>
          <motion.p initial={{opacity:0}} whileInView={{opacity:1}} viewport={{once:true}} transition={{delay:0.1}}
            className="text-slate-300 text-lg mb-10">
            Join 50,000+ professionals who've improved their resume with ResumeIQ. Free, instant, no sign-up required.
          </motion.p>
          <motion.button
            whileHover={{scale:1.05}} whileTap={{scale:0.97}}
            onClick={() => document.getElementById('analyzer')?.scrollIntoView({behavior:'smooth'})}
            className="px-10 py-5 rounded-2xl font-bold text-white text-xl transition-all"
            style={{background:'linear-gradient(135deg,#10b981,#06b6d4)', boxShadow:'0 0 40px rgba(16,185,129,0.4)'}}>
            Check My Resume — It's Free →
          </motion.button>
          <p className="text-slate-500 text-sm mt-4">No account · No credit card · Takes 30 seconds</p>
        </div>
      </section>

      <Footer/>
    </div>
  );
}
